// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt___Avancerad_.NET_Team_Super_Ninjas.Data;

#nullable disable

namespace Projekt___Avancerad_.NET_Team_Super_Ninjas.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeReportModels.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "Kalle@företaget.com",
                            Name = "Kalle Gustavsson"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "Sara@företaget.com",
                            Name = "Sara Andersson"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "Johan@företaget.com",
                            Name = "Johan Svensson"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "Lisa@företaget.com",
                            Name = "Lisa Lindström"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "Anders@företaget.com",
                            Name = "Anders Nilsson"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "Emma@företaget.com",
                            Name = "Emma Bergström"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Email = "Peter@företaget.com",
                            Name = "Peter Persson"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Email = "Maria@företaget.com",
                            Name = "Maria Karlsson"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Email = "Erik@företaget.com",
                            Name = "Erik Johansson"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Email = "Anna@företaget.com",
                            Name = "Anna Ahlström"
                        });
                });

            modelBuilder.Entity("TimeReportModels.EmployeeProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeProjects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 4
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 7
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 8
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 10
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 4
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 3
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 10
                        });
                });

            modelBuilder.Entity("TimeReportModels.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Description = "Develop an online store for a retail company.",
                            Name = "E-commerce Website"
                        },
                        new
                        {
                            ProjectId = 2,
                            Description = "Create a web platform for bloggers to publish and share their content.",
                            Name = "Blog Platform"
                        },
                        new
                        {
                            ProjectId = 3,
                            Description = "Develop a fun and engaging mobile game for iOS and Android platforms.",
                            Name = "Mobile Game App"
                        });
                });

            modelBuilder.Entity("TimeReportModels.TimeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkHours")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            End = new DateTime(2023, 3, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 3, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            End = new DateTime(2023, 4, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            End = new DateTime(2023, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 2, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 7,
                            End = new DateTime(2023, 3, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 3, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 8,
                            End = new DateTime(2023, 4, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 4, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 9,
                            End = new DateTime(2023, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 10,
                            End = new DateTime(2023, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 2,
                            End = new DateTime(2023, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 3,
                            End = new DateTime(2023, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 6,
                            End = new DateTime(2023, 1, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 7,
                            End = new DateTime(2023, 1, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 8,
                            End = new DateTime(2023, 1, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 9, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 1,
                            End = new DateTime(2023, 3, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 3, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 2,
                            End = new DateTime(2023, 4, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 4, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 3,
                            End = new DateTime(2023, 5, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 6,
                            End = new DateTime(2023, 3, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 3, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 7,
                            End = new DateTime(2023, 4, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 8,
                            End = new DateTime(2023, 5, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 1, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2023, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkHours = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("TimeReportModels.EmployeeProject", b =>
                {
                    b.HasOne("TimeReportModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeReportModels.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeReportModels.TimeReport", b =>
                {
                    b.HasOne("TimeReportModels.Employee", "Employee")
                        .WithMany("TimeReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeReportModels.Employee", b =>
                {
                    b.Navigation("TimeReports");
                });
#pragma warning restore 612, 618
        }
    }
}
